#!/usr/bin/env python3
"""
COO Weekly Report - Generate & Send to Telegram
Runs every Sunday 9pm Beijing time (13:00 UTC)
"""

import os
import sys
import requests
from datetime import datetime, timedelta
from pathlib import Path

WORKSPACE = "/root/.openclaw/workspace"
AGENTS_DIR = f"{WORKSPACE}/agents"

# Load config from agent config
from dotenv import load_dotenv
load_dotenv(f"{WORKSPACE}/agents/cio/config.env")

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

def get_week_dates():
    today = datetime.now()
    days_since_sunday = (today.weekday() + 1) % 7
    week_start = today - timedelta(days=days_since_sunday)
    week_end = week_start + timedelta(days=6)
    return week_start.strftime("%Y-%m-%d"), week_end.strftime("%Y-%m-%d")

def scan_agent_memories():
    agents = ["ken", "cio", "tan", "li", "mustafa", "pepe", "xiaomei"]
    report = {}
    for agent in agents:
        agent_dir = f"{AGENTS_DIR}/{agent}/memory"
        if not os.path.exists(agent_dir):
            continue
        report[agent] = {"daily": [], "learning": [], "evolution": []}
        for sub in ["daily", "learning", "evolution"]:
            path = f"{agent_dir}/{sub}"
            if os.path.exists(path):
                report[agent][sub] = os.listdir(path)
    return report

def scan_skills():
    skills_dir = f"{WORKSPACE}/skills"
    return os.listdir(skills_dir) if os.path.exists(skills_dir) else []

def scan_agents():
    if not os.path.exists(AGENTS_DIR):
        return []
    return [d for d in os.listdir(AGENTS_DIR) if os.path.isdir(f"{AGENTS_DIR}/{d}")]

def generate_report():
    week_start, week_end = get_week_dates()
    week_num = datetime.now().isocalendar()[1]
    
    agent_memories = scan_agent_memories()
    skills = scan_skills()
    agents = scan_agents()
    
    roles = {"ken": "Polymarket Analyst", "cio": "Investment Officer", 
             "tan": "Quant Strategy", "li": "CTO Web3", "mustafa": "Intern",
             "pepe": "Assistant", "xiaomei": "Content Creator"}
    
    # Build compact report
    report = f"""🏢 *COO 周报* - 第{week_num}周
{week_start} ~ {week_end}

---
📊 *团队*
"""
    for agent in agents:
        role = roles.get(agent, "TBD")
        mem = agent_memories.get(agent, {})
        total = sum(len(mem.get(k, [])) for k in ["daily", "learning", "evolution"])
        report += f"• {agent}: {role} ({total}条)\n"
    
    # Memory stats
    total_d = sum(len(agent_memories.get(a, {}).get("daily", [])) for a in agents)
    total_l = sum(len(agent_memories.get(a, {}).get("learning", [])) for a in agents)
    total_e = sum(len(agent_memories.get(a, {}).get("evolution", [])) for a in agents)
    
    report += f"""
---
🧠 *记忆*: {total_d} daily / {total_l} learning / {total_e} evolution
🛠️ *Skills*: {len(skills)}个

---
✅ *本周完成*
• CIO Agent 创建
• 5层记忆体系建立  
• Self-Evolve 激活
• Polymarket 术语学习

---
🔜 *下周重点*
1. Ken Polymarket 实际分析
2. CIO 报告测试
3. LanceDB 部署
4. 跨Agent知识共享

---
💡 *建议*
• 让Ken活跃产出
• 解决CIO API限制
• 建立知识共享

---
_Generated by Jarvis (COO)_
"""
    return report

def send_telegram(message):
    if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_ID:
        print("⚠️ Telegram not configured")
        return False
    
    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
    try:
        resp = requests.post(url, json={"chat_id": TELEGRAM_CHAT_ID, "text": message, "parse_mode": "Markdown"})
        return resp.status_code == 200
    except:
        return False

def main():
    print("🏢 COO Weekly Report")
    
    report = generate_report()
    
    # Save locally
    output_dir = f"{WORKSPACE}/jarvis_memory/reports"
    os.makedirs(output_dir, exist_ok=True)
    filename = f"{output_dir}/weekly-{datetime.now().strftime('%Y-%m-%d')}.md"
    with open(filename, 'w') as f:
        f.write(report)
    
    # Send to Telegram
    if send_telegram(report):
        print("✅ Report sent to Telegram")
    else:
        print("⚠️ Telegram send failed, saved locally")
    
    print(f"📄 {filename}")

if __name__ == "__main__":
    main()