#!/usr/bin/env python3
"""
Jarvis Weekly Report Generator
Generates weekly status report for the team
"""

import os
import subprocess
from datetime import datetime, timedelta

WORKSPACE = "/root/.openclaw/workspace"
REPORT_CHAT_ID = "8591571345"
TELEGRAM_BOT_TOKEN = "8269082567:AAFS7XtOg5qyh3Svdk5c0CF8KkbNW8muY-4"

def get_cron_status():
    """Check active cron jobs"""
    result = subprocess.run(
        ["crontab", "-l"], capture_output=True, text=True
    )
    jobs = [l for l in result.stdout.split('\n') if l and not l.startswith('#')]
    return len(jobs)

def get_system_status():
    """Get system resource status"""
    # Memory
    with open('/proc/meminfo') as f:
        lines = f.readlines()
    mem_total = int(lines[0].split()[1]) / 1024 / 1024
    mem_available = int(lines[2].split()[1]) / 1024 / 1024
    mem_used_pct = (1 - mem_available/mem_total) * 100
    
    # Disk
    result = subprocess.run(
        ["df", "-h", "/"], capture_output=True, text=True
    )
    disk = result.stdout.split('\n')[1].split()[4]
    
    return {
        'memory_used_pct': round(mem_used_pct, 1),
        'memory_available_gb': round(mem_available, 1),
        'disk_used_pct': disk
    }

def get_agent_status():
    """Check agent workspaces"""
    agents = ['alex', 'ken', 'gerri', 'tan', 'karl', 'frank']
    status = {}
    
    for agent in agents:
        agent_path = f"{WORKSPACE}/agents/{agent}"
        if os.path.exists(agent_path):
            # Check for session state
            state_file = f"{agent_path}/memory/SESSION-STATE.md"
            if os.path.exists(state_file):
                with open(state_file) as f:
                    content = f.read()
                    # Try to extract last updated
                    for line in content.split('\n'):
                        if 'Last updated' in line or 'last updated' in line:
                            status[agent] = line.strip()
                            break
                    else:
                        status[agent] = "Active"
            else:
                status[agent] = "Workspace exists"
        else:
            status[agent] = "Not found"
    
    return status

def get_cron_logs():
    """Get recent cron execution logs"""
    logs = {}
    
    # Ken
    try:
        with open(f"{WORKSPACE}/agents/ken/cron.log") as f:
            lines = f.readlines()
            logs['ken'] = lines[-5:] if len(lines) > 5 else lines
    except:
        logs['ken'] = []
    
    # Alex
    try:
        with open(f"{WORKSPACE}/agents/alex/health_cron.log") as f:
            lines = f.readlines()
            logs['alex'] = lines[-3:] if len(lines) > 3 else lines
    except:
        logs['alex'] = []
    
    return logs

def generate_report():
    """Generate the weekly report"""
    system = get_system_status()
    agents = get_agent_status()
    cron_count = get_cron_status()
    logs = get_cron_logs()
    
    report = f"""📊 *Jarvis 周报*
📅 {datetime.now().strftime('%Y-%m-%d %H:%M')} UTC (第{((datetime(2026,1,1) - datetime.now()).days // 7) + 1}周)

═══════════════════════════════════════

🔧 *系统状态*
- 内存使用: {system['memory_used_pct']}% ({system['memory_available_gb']}GB 可用)
- 磁盘使用: {system['disk_used_pct']}
- Cron 任务: {cron_count} 个活跃

═══════════════════════════════════════

👥 *团队状态*
"""
    
    agent_names = {
        'alex': '🔧 Alex (CTO - Web3)',
        'ken': '📊 Ken (Polymarket)',
        'gerri': '🏛️ Gerri (CIO)',
        'tan': '🧮 Tan (Quant)',
        'karl': '💰 Karl (CFO)',
        'frank': '⚖️ Frank (法务)'
    }
    
    for agent, status in agents.items():
        name = agent_names.get(agent, agent)
        report += f"\n{name}\n   └ {status}"
    
    report += f"""

═══════════════════════════════════════

📝 *本周大事*

✅ 2026-02-27: SingLink VPN 监控上线
   - Alex 每日监控 singlinkapp.com
   - 服务成立于 2026-01-01 (约2个月)
   - 每天 14:00 UTC 自动推送

✅ 2026-02-26: 团队架构重组
   - 新增 CFO Karl, 法务 Frank
   - Gerri 任命为 CIO
   
⚠️ 系统警告:
   - 内存使用较高 (需关注)
   - SSH 暴力破解尝试频繁 (安全正常)

═══════════════════════════════════════

📅 *下周计划*
- [ ] Ken: Polymarket 数据分析优化
- [ ] Alex: 更多 Web3 项目监控
- [ ] Gerri: 宏观经济报告
- [ ] Tan: 期权策略开发

═══════════════════════════════════════

💡 *收入目标进度*
目标: 每月至少 10 天 RMB
当前: 待更新

_Generated by Jarvis v1.4.0_
"""
    
    return report

def send_telegram(message):
    """Send to Telegram"""
    try:
        import urllib.request
        import urllib.parse
        
        url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
        data = urllib.parse.urlencode({
            'chat_id': REPORT_CHAT_ID,
            'text': message,
            'parse_mode': 'Markdown'
        }).encode()
        
        req = Request(url, data=data, method='POST')
        with urlopen(req) as response:
            return response.read()
    except Exception as e:
        print(f"Error: {e}")
        return None

def main():
    print(f"Generating Weekly Report... {datetime.now()}")
    
    report = generate_report()
    print(report)
    
    # Save to file
    with open(f"{WORKSPACE}/memory/weekly-report-{datetime.now().strftime('%Y-%m-%d')}.md", 'w') as f:
        f.write(f"# Jarvis Weekly Report\n\n{report}\n\n---\nGenerated: {datetime.now().isoformat()}")
    
    # Send to Telegram
    send_telegram(report)
    print("\n✅ Report sent to Telegram!")
    
    return 0

if __name__ == "__main__":
    exit(main())