#!/usr/bin/env node
/**
 * Polymarket Library Hierarchical Generator
 * 
 * Convert flat trader list to hierarchical structure
 */

const fs = require('fs');
const path = require('path');

const TRADERS = {
    // A. High-Frequency
    'A1': { name: 'kingofcoin_flips', pnl: 700000, category: 'High-Frequency' },
    'A2': { name: 'gabagool22', pnl: 10000, category: 'High-Frequency' },
    'A3': { name: '0x4460', pnl: 87000, category: 'High-Frequency' },
    
    // B. Weather
    'B1': { name: '0x594edB', pnl: 30000, category: 'Weather' },
    
    // C. NegRisk
    'C7': { name: 'PolycoolApp', pnl: 4476569, category: 'NegRisk' },
    'C6': { name: 'HolyMoses7', pnl: 2578, category: 'NegRisk' },
    'C3': { name: 'copenzafan', pnl: -40955, category: 'NegRisk' },
    
    // F. BTC High-Frequency
    'F6': { name: 'OpenClaw', pnl: 386000, category: 'BTC-HF' },
    'F5': { name: 'Demphu.finite', pnl: 91599, category: 'BTC-HF' },
    'F4': { name: 'vague-sourdough', pnl: 58712, category: 'BTC-HF' },
    
    // G. Pending
    'G1': { name: 'mikocrypto11', pnl: 0, category: 'Pending' },
    'G2': { name: 'xpredicter', pnl: 0, category: 'Pending' },
    'G3': { name: 'k1rallik', pnl: 0, category: 'Pending' }
};

class PolymarketHierarchical {
    constructor() {
        this.basePath = '/root/.openclaw/workspace/polymarket_monitor';
        this.initStructure();
    }
    
    initStructure() {
        const layers = ['L0_Domains', 'L1_Files', 'L2_Content'];
        const categories = ['High-Frequency', 'Weather', 'NegRisk', 'BTC-HF', 'Pending'];
        
        for (const layer of layers) {
            for (const cat of categories) {
                const dir = path.join(this.basePath, layer, cat);
                fs.mkdirSync(dir, { recursive: true });
            }
        }
    }
    
    generate() {
        console.log('\n' + '='*70);
        console.log('  Polymarket Library - Hierarchical Generator v1.0');
        console.log('='*70);
        console.log('');
        
        // Generate L0: Domain Index
        this.generateL0();
        
        // Generate L1: Category Files
        this.generateL1();
        
        // Generate L2: Trader Chunks
        this.generateL2();
        
        // Generate Summary
        this.generateSummary();
        
        console.log('');
        console.log('='*70);
        console.log('  ✅ Hierarchical Structure Generated!');
        console.log('='*70);
    }
    
    generateL0() {
        console.log('📦 Generating L0: Domain Index...');
        
        const content = `# Polymarket Trader Library - L0 Domain Index

**Category:** Cryptocurrency / Prediction Markets
**Version:** v1.3
**Generated:** ${new Date().toISOString()}

## Domains

| Domain | Traders | Total P&L |
|--------|---------|-----------|
| High-Frequency | 3 | ~$800K |
| Weather | 1 | $30K |
| NegRisk | 3 | ~$4.4M |
| BTC High-Frequency | 3 | ~$535K |
| Pending Verification | 3 | $0 |

## Quick Links

- [High-Frequency](./High-Frequency/index.md)
- [Weather](./Weather/index.md)
- [NegRisk](./NegRisk/index.md)
- [BTC-HF](./BTC-HF/index.md)
- [Pending](./Pending/index.md)

---
*Generated by Hierarchical Generator v1.0*
`;
        
        fs.writeFileSync(
            path.join(this.basePath, 'L0_Domains', 'index.md'),
            content
        );
        
        console.log('   ✅ L0_Domains/index.md');
    }
    
    generateL1() {
        console.log('📦 Generating L1: Category Files...');
        
        const categories = {
            'High-Frequency': {
                desc: '5-15 minute scalping strategies',
                count: 3,
                pnl: 797000
            },
            'Weather': {
                desc: 'Weather markets with NOAA data',
                count: 1,
                pnl: 30000
            },
            'NegRisk': {
                desc: 'NegRisk category strategies',
                count: 3,
                pnl: 4475192
            },
            'BTC-HF': {
                desc: '5-minute BTC/ETH high-frequency arbitrage',
                count: 3,
                pnl: 536311
            },
            'Pending': {
                desc: 'Awaiting wallet address verification',
                count: 3,
                pnl: 0
            }
        };
        
        for (const [cat, info] of Object.entries(categories)) {
            const content = `# ${cat}

**Description:** ${info.desc}
**Trader Count:** ${info.count}
**Total P&L:** $${info.pnl.toLocaleString()}

## Traders

| ID | Name | P&L |
|----|------|-----|
${Object.entries(TRADERS)
    .filter(([_, t]) => t.category === cat)
    .map(([id, t]) => `| ${id} | ${t.name} | $${t.pnl.toLocaleString()} |`)
    .join('\n')}

## Performance

${info.pnl > 0 ? '✅ Profitable' : '⏳ Pending'}

---
*Generated: ${new Date().toISOString()}*
`;
            
            fs.writeFileSync(
                path.join(this.basePath, 'L1_Files', cat, 'index.md'),
                content
            );
            
            console.log(`   ✅ L1_Files/${cat}/index.md`);
        }
    }
    
    generateL2() {
        console.log('📦 Generating L2: Trader Chunks...');
        
        let count = 0;
        
        for (const [id, trader] of Object.entries(TRADERS)) {
            const chunkDir = path.join(this.basePath, 'L2_Content', trader.category);
            const filename = `${id}_${trader.name}.md`;
            
            const content = `# ${id}: ${trader.name}

**Category:** ${trader.category}
**P&L:** $${trader.pnl.toLocaleString()}
**Generated:** ${new Date().toISOString()}

## Trader Information

- **ID:** ${id}
- **Name:** ${trader.name}
- **Category:** ${trader.category}
- **Profit/Loss:** $${trader.pnl.toLocaleString()}

## Status

${trader.pnl > 0 ? '✅ Active/Profitable' : trader.pnl < 0 ? '⚠️ Active/Loss' : '⏳ Pending Verification'}

---
*Generated by Hierarchical Generator*
`;
            
            fs.writeFileSync(path.join(chunkDir, filename), content);
            count++;
        }
        
        console.log(`   ✅ L2_Content: ${count} trader chunks`);
    }
    
    generateSummary() {
        const summary = {
            generatedAt: new Date().toISOString(),
            version: 'v1.3',
            structure: {
                L0_Domains: ['index.md'],
                L1_Files: ['High-Frequency', 'Weather', 'NegRisk', 'BTC-HF', 'Pending'],
                L2_Content: ['High-Frequency (3)', 'Weather (1)', 'NegRisk (3)', 'BTC-HF (3)', 'Pending (3)']
            },
            statistics: {
                totalTraders: Object.keys(TRADERS).length,
                categories: 5,
                totalPnL: Object.values(TRADERS).reduce((sum, t) => sum + t.pnl, 0)
            }
        };
        
        fs.writeFileSync(
            path.join(this.basePath, 'HIERARCHICAL_SUMMARY.json'),
            JSON.stringify(summary, null, 2)
        );
        
        console.log('   ✅ HIERARCHICAL_SUMMARY.json');
    }
}

async function main() {
    const generator = new PolymarketHierarchical();
    generator.generate();
}

main().catch(console.error);
